print('Tratamento de palavras com upper lower replace e split')
nome = input('Digite seu nome: ')
print(f'Seu nome em maíscula é {nome.upper()}. ')
print(f'Seu nome em minuscula é {nome.lower()}. ')
nome0 = nome.replace(' ', '')
print(f'A quantidade de letra é {len(nome0)}. ')
nome1 = nome.split()
print(f'A quantidade de letra no primeiro nome é {len(nome1[0])}. ')

#Correção
nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiuscula é {}. '.format(nome.upper()))
print('Seu nome em minuscula é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras. '.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras. '.format(separa[0], len(separa[0])))