print('Tratamento de palavras com upper lower replace e split')
nome = input('Digite seu nome: ')
print(nome.upper())
print(nome.lower())
nome0 = nome.replace(' ', '')
print(f'A quantidade de letra é {len(nome0)}. ')
nome1 = nome.split()
print(f'A quantidade de letra no primeiro nome é {len(nome1[0])}. ')
